export enum ACCOUNT_TYPE{
    STUDENT = "STUDENT",
    EMPLOYER = "EMPLOYER",
}

export enum ACCOUNT_STATUS{
    APROVAL_PENDING =  "APROVAL_PENDING", 
    ACTIVE = "ACTIVE", 
    INACTIVE = "INACTIVE", 
    BLOCKED = "BLOCKED", 
    DELETED = "DELETED"
}
